-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "isBracket" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "slPrice" DOUBLE PRECISION,
ADD COLUMN     "slQty" DOUBLE PRECISION,
ADD COLUMN     "tpPrice" DOUBLE PRECISION,
ADD COLUMN     "tpQty" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Position" ADD COLUMN     "slHit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "slPrice" DOUBLE PRECISION,
ADD COLUMN     "slQty" DOUBLE PRECISION,
ADD COLUMN     "tpHit" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tpPrice" DOUBLE PRECISION,
ADD COLUMN     "tpQty" DOUBLE PRECISION;
